### ISSUE TITLE
It doens't work

### ISSUE THREAD

**Issue by vladimireduardo** [didinj/mevn-stack-vue-2#2]
**Environment:**
- MacOS High Sierra 10.13.6
- Node Version: v8.11.3
- npm version: 5.6.0
- My local folder: /Users/stackmachine/Documents/Code/stacks/mevn/mevn-secure (only for understand the error log)

**Errors:**
1. After run "npm start" i had too many errors in http://localhost:3000  like:
`GET /_next/webpack-hmr 500 1.452 ms - 14
{ Error: Not Found
    at /Users/stackmachine/Documents/Code/stacks/mevn/mevn-secure/app.js:29:13
    at Layer.handle [as handle_request] (/Users/stackmachine/Documents/Code/stacks/mevn/mevn-secure/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/stackmachine/Documents/Code/stacks/mevn/mevn-secure/node_modules/express/lib/router/index.js:317:13)
    at /Users/stackmachine/Documents/Code/stacks/mevn/mevn-secure/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/stackmachine/Documents/Code/stacks/mevn/mevn-secure/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/stackmachine/Documents/Code/stacks/mevn/mevn-secure/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/Users/stackmachine/Documents/Code/stacks/mevn/mevn-secure/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)
    at SendStream.error (/Users/stackmachine/Documents/Code/stacks/mevn/mevn-secure/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/stackmachine/Documents/Code/stacks/mevn/mevn-secure/node_modules/send/index.js:421:12)
    at next (/Users/stackmachine/Documents/Code/stacks/mevn/mevn-secure/node_modules/send/index.js:736:16)
    at onstat (/Users/stackmachine/Documents/Code/stacks/mevn/mevn-secure/node_modules/send/index.js:725:14)
    at FSReqWrap.oncomplete (fs.js:152:21) status: 404 }
GET /_next/webpack-hmr 500 0.737 ms - 14`
2. The login page didn't appear and when i went to /book it didn't redirect to login

**Comment by alinaugustin** [comment]
It works. Maybe u didnt configured that: mongoose.connect('mongodb://localhost:27017/mevn-secure', { promiseLibrary: require('bluebird') })

**Comment by vladimireduardo** [comment]
> It works. Maybe u didnt configured that: mongoose.connect('mongodb://localhost:27017/mevn-secure', { promiseLibrary: require('bluebird') })

yes it works! thanks
